name: Release Drafter
on:
    workflow_dispatch:
        inputs:
            version-bump:
                description: The scale of the version bump required for semver compatibility
                required: true
                default: automatic
                type: choice
                options:
                    - automatic
                    - patch
                    - minor
                    - major
            type:
                description: The type of release to make
                required: true
                default: release-candidate
                type: choice
                options:
                    - release-candidate
                    - release
                    - hotfix
            previous-version:
                description: What release to use as a base for release note purposes, defaults to the latest stable release.
                required: false
                type: string
            matrix-js-sdk:
                description: JS SDK version to use (current|X.Y.Z)
                required: false
                default: current
                type: string
concurrency: ${{ github.workflow }}
jobs:
    draft:
        uses: matrix-org/matrix-js-sdk/.github/workflows/release-drafter-action.yml@develop
        secrets: inherit
        with:
            version-bump: ${{ inputs.version-bump }}
            previous-version: ${{ inputs.previous-version }}
            final: ${{ inputs.type != 'release-candidate' }}
            yarn-pack: true
            dependencies: |
                matrix-js-sdk=${{ inputs.matrix-js-sdk }}
